config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'friends#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]

  def index
  end
  
  def about
    @about_me = "My name is Divij Jain!"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
<% if friend.errors.any? %>
<div style="color: red">
  <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

  <ul>
    <% friend.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="mb-3">
  <%= form.text_field :first_name, class:"form-control", placeholder: "First Name" %>
</div>

<div class="mb-3">
  <%= form.text_field :last_name, class:"form-control", placeholder: "Last Name" %>
</div>

<div class="mb-3">
  <%= form.text_field :email, class:"form-control", placeholder: "Email Address" %>
</div>

<div class="mb-3">
  <%= form.text_field :phone, class:"form-control", placeholder: "Phone Number" %>
</div>

<div class="mb-3">
  <%= form.text_field :twitter, class:"form-control", placeholder: "Twitter" %>
</div>

<div class="mb-3">
  <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
</div>

<div class="mb-3">
  <%= form.submit class:"btn btn-dark btn-md mt-2" %>
</div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <tr>
    <td> <%= link_to friend.first_name+' '+friend.last_name, friend %> </td>
    <td> <%= friend.email %> </td>
    <td> <%= friend.phone %> </td>
    <td> <%= friend.twitter %> </td>
  </tr>
</div>

app/views/friends/edit.html.erb
<h1>Edit a Friend Information</h1>
<br>
<%= render "form", friend: @friend %>
<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-dark btn-sm" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <h1>List of Friends</h1>
  <br>
  <div id="friends">
    <table class="table table-striped table-bordered">
      <thead class="table-dark">
        <tr>
          <th> Name </th>
          <th> Email </th>
          <th> Phone Number </th>
          <th> Twitter </th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <% if friend.user == current_user %>
            <%= render friend %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <%= link_to "New friend", new_friend_path, class: "btn btn-dark btn-md" %>
<% else %>
  <h1 class="display-1"> Friends List</h1>
  <p class="lead"> A application to keep a track of all your friends and their information ✨ </p>
<% end %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>
<br>

<%= render "form", friend: @friend %>


<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/friends/show.html.erb
<br>
<div class="container p-4" style="background-color:	#e9ecef; border-radius: .3rem;">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %>
  </p>
  <hr class="my-4">
  <div>
    <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-dark btn-sm" %>
    <%= link_to "Back", friends_path, class:"btn btn-dark btn-sm" %>
    <%= button_to "Delete this friend", @friend, method: :delete, class: "btn btn-danger btn-sm mt-1" %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Friend App', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
                </li>
                    <li class="nav-item">
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
                </li>

                <li class="nav-item">
                    <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
                </li>

                <li class="nav-item">
                    <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
                </li>
            <% end %>
            <li class="nav-item">
                <%= link_to "About Us", home_about_path, class:"nav-link" %>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

app/views/home/about.html.erb
<h1 class="display-2">About Us</h1>
<p class="lead"> <%= @about_me%> </p>
<p> I am a developer and I created this website to use it as a database for your friends! 👨‍💻 </p>

app/views/home/index.html.erb
<h1>Index Page</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-secondary alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <title>FriendsList App</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render 'home/header' %>

  <div class="container">
    <br>
    <% if notice %>
    <%= render 'layouts/alerts' %>
    <% end %>

    <br>
    <%= yield %>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
</body>

</html>